### ISSUE TITLE
Proper way to set permission?

### ISSUE THREAD

**Issue by xnuk** [Xe/xn--ts9h#6]
https://github.com/Xe/xn--ts9h/blob/8f1dda8e53a500ea1d2a31fbc3547c66d4f91d8e/Cargo.toml#L11

Seems setting permission to 6755 is a recommended way, I followed that direction:
```
$ sudo cp target/release/xn--ts9h /usr/bin/🥺
$ sudo chown root /usr/bin/🥺
$ sudo chmod 6755 /usr/bin/🥺
$ stat /usr/bin/🥺
  File: /usr/bin/🥺
  Size: 321840          Blocks: 632        IO Block: 4096   regular file
Device: 8,32    Inode: 183118      Links: 1
Access: (6755/-rwsr-sr-x)  Uid: (    0/    root)   Gid: (    0/    root)
...

$ 🥺 id
uid=0(root) gid=0(root) groups=0(root),998(wheel),1000(xnuk)
```

Which is nice, but this means any user in this computer can access to root:

```
$ sudo -u git 🥺 id
uid=0(root) gid=0(root) groups=0(root),975(git)
```

Setting `chgrp wheel` and `chmod 6754` is probably what I wanted, but I still don't fully understand the 4-digit permission system:
```
$ sudo chgrp wheel /usr/bin/🥺
$ sudo chmod 6754 /usr/bin/🥺
$ stat /usr/bin/🥺
  File: /usr/bin/🥺
  Size: 321840          Blocks: 632        IO Block: 4096   regular file
Device: 8,32    Inode: 183118      Links: 1
Access: (6754/-rwsr-sr--)  Uid: (    0/    root)   Gid: (  998/   wheel)
...

$ 🥺 id
uid=0(root) gid=0(root) groups=0(root),998(wheel),1000(xnuk)
$ sudo -u git 🥺 id
sudo: unable to execute /usr/bin/🥺: Permission denied
```

So I want to ask:
1. am i doing right or could you write some guide for this
2. or is it intended that any user can access to root

**Comment by Xe** [comment]
It is intended that any user can access root with this tool. This is a satirical tool that is intended to make you rethink the concept of privilege escalation. Hint: it's almost always NOT the pattern you want.
